[versions]
preference = "1.2.1"
xposed-legacy = "82"
agp = "8.3.2"
colorpicker = "1.1.0"
dexkit = "2.0.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
nav = "2.7.6"

[libraries]
colorpicker = { module = "com.jaredrummler:colorpicker", version.ref = "colorpicker" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
libxposed-legacy = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed-legacy" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }

androidx-activity = { module = "androidx.activity:activity", version = "1.8.2" }
androidx-browser = { module = "androidx.browser:browser", version = "1.7.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-core = { module = "androidx.core:core", version = "1.12.0" }
androidx-fragment = { module = "androidx.fragment:fragment", version = "1.6.2" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "nav" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "nav" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.2.0-alpha01" }

rikkax-appcompat = { module = "dev.rikka.rikkax.appcompat:appcompat", version = "1.6.1" }
rikkax-core = { module = "dev.rikka.rikkax.core:core", version = "1.4.1" }
rikkax-insets = { module = "dev.rikka.rikkax.insets:insets", version = "1.3.0" }
rikkax-layoutinflater = { module = "dev.rikka.rikkax.layoutinflater:layoutinflater", version = "1.3.0" }
rikkax-material = { module = "dev.rikka.rikkax.material:material", version = "2.7.0" }
rikkax-material-preference = { module = "dev.rikka.rikkax.material:material-preference", version = "2.0.0" }
rikkax-preference = { module = "dev.rikka.rikkax.material:material-preference", version = "2.0.0" }
rikkax-recyclerview = { module = "dev.rikka.rikkax.recyclerview:recyclerview-ktx", version = "1.3.2" }
rikkax-widget-borderview = { module = "dev.rikka.rikkax.widget:borderview", version = "1.1.0" }
rikkax-widget-mainswitchbar = { module = "dev.rikka.rikkax.widget:mainswitchbar", version = "1.0.2" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

